---
# This playbook appends groups to a specific user
# usage aplaybook -l <machines> --extra-vars "username=<value> group=<value>"
- name: Add user to group
  hosts: all
  become: true
  vars:
    username: studente
    group: dialout
  tasks:
    - name: Add user to group
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        groups: "{{ group }}"
        append: yes
