---
# This playbook changes a default local user description
# usage aplaybook -l <machines> --extra-vars "username=<value> description=<value>"
# 
- name: Change user 
  hosts: all
  become: true
  vars:
    username: studente
    description: studente
  tasks:
    - name: Change user comment
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        comment: "{{ description }}"
