---
# This playbook changes a specified local user password
# usage aplaybook -l <machines> --extra-vars "username=<value> password=<value>"
- name: Change local user password
  hosts: all
  become: true
  vars:
    username: 'tecnico'
    password: 'supersecretpassword'
  tasks:
    - name: Change Password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
