---
# Install non standard packages
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Clean up previous installations of Processing
       ansible.builtin.shell: rm -rf /opt/processing*
     - name: Copy Processing from server
       ansible.builtin.copy:
         src: /opt/ansible_data/applications/processing-4.0.1-linux-x64.tgz
         dest: /opt
     - name: decompress Processing
       ansible.builtin.shell: |
         cd /opt
         tar zxvf processing-4.0.1-linux-x64.tgz
         rm processing-4.0.1-linux-x64.tgz
         sudo -u studente /opt/processing-4.0.1/install.sh
         exit 0 	
