---
# Install non standard packages
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Clean up old Johnny dist
       ansible.builtin.shell: rm -rf /home/studente/johnny
     - name: Copy Johnny from server
       ansible.builtin.copy:
         src: /opt/ansible_data/applications/johnny.tar.bz2
         dest: /home/studente/
         owner: studente
         group: studente
         mode: '644'
     - name: untarbz Johnny
       ansible.builtin.shell: |
         cd /home/studente
         tar jxvf johnny.tar.bz2
         rm johnny.tar.bz2
         chown studente.studente -R johnny
         exit 0 	
