---
# 
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy folder contents recursively
      ansible.windows.win_copy:
          src: /opt/ansible/scripts/monitoring/
          dest: C:\users\tecnico

    - name: Change the working directory to somedir/ before executing the command
      ansible.windows.win_shell: C:\users\tecnico\check_hdd_encryption.ps1
      register: delete_results
    - name: Grab result output
      fetch: src={{ inventory_hostname }}.csv dest=bitl_results/ flat=yes

