---
# This playbook configures all non standard apt repos
# this is used on labs computers
# this playbook is Linux Only
 - name: Configure apt repository
   hosts: all
   become: true
   gather_facts: no
   tasks:
   - name: Wait for connection
     wait_for_connection:
       delay: 60
       timeout: 400
   - name: Add TeXstudio  apt_repository
     ansible.builtin.apt_repository:
       repo: ppa:sunderme/texstudio
       state: present
   - name: Add Veyon apt_repository
     ansible.builtin.apt_repository:
       repo: ppa:veyon/stable
       state: present
   - name: Add Vuesz apt_repository
     ansible.builtin.apt_repository:
        repo: ppa:jeremysanders/ppa
        state: present
   - name: Add Vscode repo
     ansible.builtin.shell: |
         sudo rm -rf  /etc/apt/sources.list.d/vscode.list
         sudo curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
         sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
         sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
         exit 0    
   - name: Add google chrome repo
     ansible.builtin.shell: |
         sudo rm -rf  /etc/apt/sources.list.d/googl*
         sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
         sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
         exit 0  
