---
# disable overlayroot
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Disable overlay fs
       ansible.builtin.shell: |
          overlayroot-chroot rm /etc/overlayroot.local.conf
          exit 0
     - name: Reboot
       reboot: