---
# This playbook disables overlayroot fs 
# inside computer labs
# this playbook is Linux Only

- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Disable overlay fs
       ansible.builtin.shell: |
          overlayroot-chroot rm /etc/overlayroot.local.conf
          exit 0
     - name: Reboot
       reboot:
