---
# This playbook enables overlayroot fs
# onto labs computers
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Enable overlay fs
       ansible.builtin.shell: |
          echo overlayroot="tmpfs:swap=1"  | sudo tee /etc/overlayroot.local.conf
          exit 0
     - name: Shutdown 
       community.general.shutdown:
