---
# Install jupyte_env
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Clean up previous installations of arduino
       ansible.builtin.shell: rm -rf /opt/jupyter
     - name: Copy home env from server
       ansible.builtin.copy:
         src: /opt/ansible_data/applications/jupyter_env/jupyter.tar.bz2
         dest: /opt
     - name: decompress Data
       ansible.builtin.shell: |
         cd /opt
         tar jxvf jupyter.tar.bz2
         rm /opt/jupyter.tar.bz2
         rm -f /usr/share/applications/jupyter.desktop
         cp /opt/jupyter/jupyter.desktop /usr/share/applications/jupyter.desktop
         mkdir -p /home/studente/.jupyter
         cp /opt/jupyter/jupyter_lab_config.py /home/studente/.jupyter
         chown studente.studente -R /home/studente/.jupyter
         exit 0 	
