---
# set default shell to cmd
- hosts: all
  gather_facts: no
  tasks:
    - name: set the default shell to cmd
      win_regedit:
       path: HKLM:\SOFTWARE\OpenSSH
       name: DefaultShell
       state: absent