---
# set default shell to cmd
- hosts: all
  gather_facts: no
  tasks:
    - name: Disable Fastboot
      win_regedit:
       path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power
       name: HiberBootEnabled
       data: 0
       type: dword
       state: present
       