---
# set default shell to cmd
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy folder contents recursively
      ansible.windows.win_copy:
          src: /opt/ansible/scripts/power/
          dest: C:\users\tecnico

    - name: Change the working directory to somedir/ before executing the command
      ansible.windows.win_shell: C:\users\tecnico\wol_windows\run_script.cmd
