---
# This playbook sets some standard grub options 
# in order to use pxe boot
# this playbook is Linux only
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Copy new configuration file
       ansible.builtin.copy:
         src: /opt/ansible/configurations/grub/grub
         dest: /etc/default/
         owner: root
         group: root
         mode: '644'
     - name: Update grub config dir
       ansible.builtin.shell: |
             sudo update-grub 
