---

- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Set hostname
      ansible.builtin.hostname: 
        name="{{ inventory_hostname }}"
    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="127.0.1.1 {{ inventory_hostname }}"
        regexp="^127.0.1.1"
