---
 - name: Update all packages
   hosts: lab1,!lab1-n128,!lab1-n126
   serial: 1
   become: true
   gather_facts: no
   tasks:
   - name: Wait for connection
     wait_for_connection:
   - name: Update packages database
     apt:
       update_cache: yes
   - name: Update all packages to their latest version
     ansible.builtin.apt:
       name: "*"
       state: latest