---
# Wake desktops, wait for them to become ready and continue playbook
- hosts: laptop
  gather_facts: no
  tasks:
  - name: Send magic Wake-On-Lan packet to turn on individual systems
    wakeonlan:
      mac: '{{ mac }}'
      broadcast: '{{ broadcast }}'
    delegate_to: localhost
    async: 100
    poll: 0

  - name: Wait for system to become reachable
    wait_for_connection:
      timeout: 50
