---
# distribute wallpapers
- hosts: all
  become: true
  gather_facts: no
  tasks:
     - name: Disable overlay fs
       ansible.builtin.shell: |
          /usr/local/bin/overlayroot -n
          exit 0
     - name: Reboot after disable overlay fs
       reboot:
     - name: Wait for connection
       wait_for_connection:
         delay: 2
     - name: Create wallpapers dir
       ansible.builtin.file:
         path: /usr/local/share/wallpapers
         state: directory
         mode: '0755'
     - name: Copy new configuration file
       ansible.builtin.copy:
         src: /opt/ansible_data/wallpapers/*
         dest: /usr/local/share/wallpapers
         owner: root
         group: root
         mode: '644'
